stages:
  - test

e2e_tests_manual:
  stage: test    
  when: manual   # só executa quando você clicar no botão manualmente
  script:
    - echo "Iniciando testes E2E manualmente..."
    - yarn install
    - yarn playwright install
    - yarn run e2e
    

e2e_tests_schedule:
  stage: test    
  script:
    - echo "Executando testes E2E agendados..."
    - yarn install
    - yarn playwright install
    - yarn run e2e
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never