stages:
  - test

e2e_tests_manual:
  stage: test    
  image: node:18   # imagem oficial node que jรก tem yarn
  when: manual
  script:
    - echo "Iniciando testes E2E manualmente..."
    - yarn install
    - yarn playwright install
    - yarn run e2e

e2e_tests_schedule:
  stage: test    
  image: node:18
  script:
    - echo "Executando testes E2E agendados..."
    - yarn install
    - yarn playwright install
    - yarn run e2e
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - when: never