stages:
  - test

e2e_tests_manual:
  stage: test
  tags:
    - windows
  when: manual # Dispara somente manualmente pelo botão no GitLab
  script:
    - echo "Iniciando testes E2E manualmente..."
    - yarn install
    - yarn playwright install
    - yarn run e2e
