# CI de Nível 02 - Disparo agendado

# nome do nosso 'pipeline'
name: 'Execução Agendada'

# regras de disparo (gatilhos/triggers)
#gatilho de exec agendada é o schedule

# a minuto
# b hora
# dia do mês
# mês
# dia da semana

# exemplo, agendo o regressivo para rodar toda segunda-feira pela manhã as 6 horas da manhã, logo preciso configurar assim (considerando o exemplo citado): 
# a b c d e
# 0 6 * * 1 
# https://crontab.guru/ posso usar para criar tal combinação

on:
  schedule:
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline=jobs
jobs:
  e2e-tests:

    # maquina que o job vai executar, pode consultar em https://github.com/actions/runner-images
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4 

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do playwright
      - name: Instalando playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e



